[tool.poetry]
name = "inspy_logger"
version = "0.1.0"
description = ""
authors = ["taylor <tayjaybabee@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.2"
colorlog = "^4.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
